### ISSUE TITLE
Language-neutral interface for extending?

### ISSUE THREAD

**Issue by ylxdzsw** [cornell-netlab/yates#1]
Hi, I read your papers and would like to try our prototype with Yates. However, I don't know how to program in OCaml, and it looks hard. I wonder if you could please provide a canonical interface like REST or some TCP based protocol to implement a routing module?

I noticed that the main method of an algorithm module is `solve`. Ideally I hope something like

```ocaml
let solve (topo:topology) (pairs:demands) : scheme =
      let data = serilize_as_json topo pairs in
      let req = http_post host port data in
      let response = get_body req in
      deserialize_to_scheme response
```

but I'm too new to OCaml to implement this. Could you please provide such a module? Thanks!

**Comment by ylxdzsw** [comment]
Hi, finally I managed to learn enough OCaml to call an external process. So thank for attention if any.

For who have the same problem, here is our (ugly but work) code [https://github.com/ylxdzsw/yates/blob/master/lib/routing/Custom.ml](https://github.com/ylxdzsw/yates/blob/master/lib/routing/Custom.ml)

**Comment by prvnkumar** [comment]
Sorry about the delayed response.
We would definitely like to include a language-neutral interface as you pointed out. I will spend some cycles on this.
Also, we welcome contributions. So, if you have a solution that you would like to contribute, feel free to create a pull request.
