### ISSUE TITLE
Hello，how I can generate the corresponding traffic demand matrix based on these given topology?

### ISSUE THREAD

**Issue by ShawnshanksGui** [cornell-netlab/yates#2]

**Comment by prvnkumar** [comment]
The code and scripts for generating traffic matrices is in [$YATES/data/prediction](https://github.com/cornell-netlab/yates/tree/master/data/prediction). To generate TMs, do the following:
1. Build:
```
$ cd $YATES/data/prediction
$ make
```
2. Parse topologies and convert into graphs. You need to do this only once.
```
$ sh scripts/generate_graph_matrix.sh
```
3. Generate traffic matrices
```
$ sh scripts/run_all_predictions.sh
```
The traffic matrices will be generated in `./matrix` directory
You can see `scripts/run_all_prediction.sh` to see how to generate TMs for other topologies

**Comment by ShawnshanksGui** [comment]
Thanks for your help!
